### PR TITLE
Add unit tests for BinaryMatrix

### PR DESCRIPTION
**Pull request by SpaceKatt**
Adds unit tests for Gso.MathLib.BinaryMatrix

Adds unit test runner (Mocha being run in the browser)

### CODE REVIEW

**Comment by jjs0sbw** [comment]
Keep up the good work..

**Comment by jjs0sbw** [comment]
It is not clear that all the tests are passing.. Do all the tests pass now?

**Comment by SpaceKatt** [comment]
All tests are passing now

**Comment by jjs0sbw** [comment]
Cool..

**Pull request merged**
